### PR TITLE
Ticket #2: Authorship proposal v2

### PR DESCRIPTION
**Pull request by regrant**
Alternate authorship listing

### CODE REVIEW

**Comment by regrant** [comment]
Example PDF: [Author_v2.pdf](https://github.com/pwrapi/powerapi_spec/files/1868695/Author_v2.pdf)

**Comment by ajyounge** [comment]
I think V2 makes more sense, has institutional associations included, and can be moved to a separate page if/when it grows to that size. I also think chair should be listed first.

**Comment by regrant** [comment]
Updated PDF: 
[PowerAPI_Community.pdf](https://github.com/pwrapi/powerapi_spec/files/2059137/PowerAPI_Community.pdf)

**Comment by regrant** [comment]
June 1st, unanimous vote yes

**Pull request merged**
